/// <reference types="cypress" />

describe('announcement', () => {
    it('announcement successfully', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#placeholder').click()
        cy.visit('http://localhost:3000/announcement')
        cy.get('#title').should('have.text', 'Pemberitahuan')
    })   

    it('announcement empty', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#placeholder').click()
        cy.visit('http://localhost:3000/announcement')
        cy.get('.text-center b').should('have.text', 'Tidak ada pemberitahuan untuk saat ini')
    })   

    it('announcement not empty', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#placeholder').click()
        cy.visit('http://localhost:3000/announcement')
        cy.get('.bg-card-task').should('have.length', 1)
    })   
})