/// <reference types="cypress" />

describe('history', () => {
    it('history successfully', () => {
        cy.viewport(1920, 1080)
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#history').click()
        cy.get('h1').should('have.text', 'Riwayat')
    })

    it('history data not empty', () => {
        cy.viewport(1920, 1080)
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#history').click()
        // cy.get('#Amet Nam poro veli').should('have.text', 'Amet Nam poro veli')
        cy.get('#1').should('have.text', 'Amet Nam porro veli')
    })

    it('history data empty', () => {
        cy.viewport(1920, 1080)
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('#history').click()
    })
})