/// <reference types="cypress" />

describe('certificate course', () => {
    // certificate dipilih
    it('certificate course successfully load', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('admin')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('.grid #card0').click()
        cy.get('#title').should('have.text', 'Amet Nam porro veli')
        cy.get('#accordion').should('have.text', 'Ina Aguilar')
        cy.get('#feedback').click()
        cy.wait(900)
        cy.get('#sertifikat').click()
        cy.get('#title').should('have.text', 'Membuat Sertifikat')
    })   

    it('certificate course not success generate', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('admin')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('#greeting').should('have.text', 'Halo!')
        cy.get('.grid #card0').click()
        cy.get('#title').should('have.text', 'Amet Nam porro veli')
        cy.get('#accordion').should('have.text', 'Ina Aguilar')
        cy.get('#feedback').click()
        cy.wait(900)
        cy.get('#sertifikat').click()
        cy.get('#title').should('have.text', 'Membuat Sertifikat')
        cy.get('#submit').click()
        cy.get('#message').should('have.text', 'tulis nama lengkap anda terlebih dahulu')
    })   

    // it('certificate course success generate', () => {
    //     cy.visit('http://localhost:3000/')
    //     cy.get('#login').click()
    //     cy.get('h2').should('have.text', 'Login Sebagai...')
    //     cy.get('#peserta').click()
    //     cy.get('#email')
    //         .type('admin')
    //     cy.get('#password')
    //         .type('password')
    //     cy.get('#login').click()
    //     cy.get('#greeting').should('have.text', 'Halo!')
    //     cy.get('.grid #card1').click()
    //     cy.get('#feedback').click()
    //     cy.wait(900)
    //     cy.get('#sertifikat').click()
    //     cy.get('#title').should('have.text', 'Membuat Sertifikat')
    //     cy.get('#input-name').type('david william')
    //     cy.get('#submit').click()
    //     cy.wait(1000)
    //     cy.get('#canvas').should('be.true')
    // })   
})