// <reference types="cypress" />

describe('task', () => {
    // render task page
    it('loads successfully task', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('.grid #card0').click()
        cy.get('#title').should('have.text', 'Amet Nam porro veli')
        cy.get('#accordion').should('have.text', 'Ina Aguilar')
        cy.get('#taskTest').click()
        cy.get('#title').should('have.text', 'Unggah Tugas')
    })

    // task send not success
    it('task send is not successfully', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('.grid #card0').click()
        cy.get('#title').should('have.text', 'Amet Nam porro veli')
        cy.get('#accordion').should('have.text', 'Ina Aguilar')
        cy.get('#taskTest').click()
        cy.get('#title').should('have.text', 'Unggah Tugas')
        cy.wait(1000)
        cy.get('#button').click()
        cy.get('#message').should('have.text', 'file tidak berhasil dikirim. coba lagi')
    })

    // task send success
    it('task send is successfully', () => {
        cy.visit('http://localhost:3000/')
        cy.get('#login').click()
        cy.get('h2').should('have.text', 'Login Sebagai...')
        cy.get('#peserta').click()
        cy.get('#email')
            .type('kader')
        cy.get('#password')
            .type('password')
        cy.get('#login').click()
        cy.get('.grid #card0').click()
        cy.get('#title').should('have.text', 'Amet Nam porro veli')
        cy.get('#accordion').should('have.text', 'Ina Aguilar')
        cy.get('#taskTest').click()
        cy.get('#title').should('have.text', 'Unggah Tugas')
        cy.wait(1000)
        cy.get('#input-file').selectFile('cypress/testing-file.txt', { action: 'drag-drop' })
        cy.get('#button').click()
        cy.get('#message').should('have.text', 'file berhasil dikirim')
    })
})